package Controller;

public enum SuggestionParams {MINBPM, MAXBPM, MINVALENCE, MAXVALENCE, MINENERGY, MAXENERGY, MINDANCEABILITY, MAXDANCEABILITY,

     MININSTRUMENTALNESS, MAXINSTRUMENTALNESS, MINACOUSTICNESS, MAXACOUSTICNESS, UNDEFINED;
}
