package Controller;

public enum SuggestionParams {MINVALENCE, MAXVALENCE, MINBPM, MAXBPM, MINACOUSTICNESS, MAXACOUSTICNESS, MINDANCEABILITY, MAXDANCEABILITY,
    MINENERGY, MAXENERGY, MININSTRUMENTALNESS, MAXINSTRUMENTALNESS
}
